### ISSUE TITLE
Mote types of messages other than text and message

### ISSUE THREAD

**Issue by marcodali** [green-api/whatsapp-chatbot-js#82]
Add support for media messages:

- Images
- Link
- Video
- Poll
- Buttons

**Comment by andreyMalyshkin** [comment]
Hello!We recive you message and took it to work!

**Comment by andreyMalyshkin** [comment]
What problem do you have with Links?

**Comment by andreyMalyshkin** [comment]
Good afternoon! Links are sent using the sendMessage method.
Currently, files can be sent using a URL using the sendFileByUrl method.
Polls are also sent using the sendPoll method.
The method for sending files from a local device is temporarily unavailable, we apologize
